apiVersion: v1
kind: ReplicationController
metadata:
  name: minio
spec:
  replicas: 2
  selector:
    app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec: 
      volumes:
        - name: storage-data
          persistentVolumeClaim:
           claimName: my-pvc-pv1
          #emptyDir: {}
      containers:
        - name: minio #minio
          image: minio/minio
          args:
            - server
            - /data
          volumeMounts:
            - name: storage-data
              mountPath: /data
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: miniostorage
          envFrom:
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 9000

--- 
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
